import 'package:json_annotation/json_annotation.dart';

part 'task.g.dart';

enum TaskStatus { pending, inProgress, completed }

enum Priority { low, medium, high }

class Subtask {
  final String title;
  final bool isCompleted;

  Subtask({required this.title, this.isCompleted = false});

  Map<String, dynamic> toJson() => {
    'title': title,
    'isCompleted': isCompleted,
  };

  factory Subtask.fromJson(Map<String, dynamic> json) => Subtask(
    title: json['title'] as String,
    isCompleted: json['isCompleted'] as bool,
  );

  // Optional: Add copyWith for Subtask if needed
  Subtask copyWith({String? title, bool? isCompleted}) {
    return Subtask(
      title: title ?? this.title,
      isCompleted: isCompleted ?? this.isCompleted,
    );
  }
}

@JsonSerializable(explicitToJson: true)
class TaskData {
  final int? id; // Nullable, as it’s generated by SQLite
  final String title;
  final DateTime completionDate; // Updated from dueDate
  final TaskStatus status;
  final String description;
  final List<Map<String, dynamic>> assignees;
  final List<Subtask>? subtasks; // Made nullable
  final List<String>? tags; // New nullable field for tags
  final Priority priority; // New field for priority

  TaskData({
    this.id, // Nullable
    required this.title,
    required this.completionDate,
    required this.status,
    required this.description,
    required this.assignees,
    this.subtasks, // Nullable
    this.tags, // Nullable
    required this.priority, // Required priority
  });

  factory TaskData.fromJson(Map<String, dynamic> json) => _$TaskDataFromJson(json);

  Map<String, dynamic> toJson() => _$TaskDataToJson(this);

  // Update copyWith method for TaskData to include priority
  TaskData copyWith({
    int? id,
    String? title,
    DateTime? completionDate,
    TaskStatus? status,
    String? description,
    List<Map<String, dynamic>>? assignees,
    List<Subtask>? subtasks,
    List<String>? tags,
    Priority? priority,
  }) {
    return TaskData(
      id: id ?? this.id,
      title: title ?? this.title,
      completionDate: completionDate ?? this.completionDate,
      status: status ?? this.status,
      description: description ?? this.description,
      assignees: assignees ?? this.assignees,
      subtasks: subtasks ?? this.subtasks,
      tags: tags ?? this.tags,
      priority: priority ?? this.priority,
    );
  }
}